"""empty message

Revision ID: f30cc9a83884
Revises: 9123960cfd9e
Create Date: 2025-03-31 08:20:48.173033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30cc9a83884'
down_revision = '9123960cfd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('played_games', schema=None) as batch_op:
        batch_op.alter_column('game_data',
               existing_type=sa.VARCHAR(length=3000),
               nullable=True)
        batch_op.alter_column('game_points',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('played_games', schema=None) as batch_op:
        batch_op.alter_column('game_points',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('game_data',
               existing_type=sa.VARCHAR(length=3000),
               nullable=False)

    # ### end Alembic commands ###
